export const wallets = {
    'mzV5lzbY4WkkYazB': {
        'id': 'get-wallet-state',
        'result': '0',
        'params': {
            'tokens': 54,
            'coins': 33,
            'is_node': 1,
            'node_address': 'address',
            'last_transaction_id': 'uint22',
            'exist': 1,
        },
    },
    'fCgWIfSCcElso4oz': {
        'id': 'get-wallet-state',
        'result': '0',
        'params': {
            'tokens': 62,
            'coins': 16,
            'is_node': 1,
            'node_address': 'address',
            'last_transaction_id': 'uint8',
            'exist': 1,
        },
    },
    '4A9g2wYbJYirc9Os': {
        'id': 'get-wallet-state',
        'result': '0',
        'params': {
            'tokens': 5,
            'coins': 25,
            'is_node': 1,
            'node_address': 'address',
            'last_transaction_id': 'uint52',
            'exist': 1,
        },
    },
    'Wg1jnyON2Z4mTy4Y': {
        'id': 'get-wallet-state',
        'result': '0',
        'params': {
            'tokens': 21,
            'coins': 11,
            'is_node': 1,
            'node_address': 'address',
            'last_transaction_id': 'uint81',
            'exist': 1,
        },
    },
    'xrgbAHXE5V486Md8': {
        'id': 'get-wallet-state',
        'result': '0',
        'params': {
            'tokens': 27,
            'coins': 6,
            'is_node': 1,
            'node_address': 'address',
            'last_transaction_id': 'uint30',
            'exist': 1,
        },
    },
    'RfHMzgPHEfkoYeGe': {
        'id': 'get-wallet-state',
        'result': '0',
        'params': {
            'tokens': 50,
            'coins': 53,
            'is_node': 1,
            'node_address': 'address',
            'last_transaction_id': 'uint67',
            'exist': 1,
        },
    },
    'gMCn6E6S5jGbjs4k': {
        'id': 'get-wallet-state',
        'result': '0',
        'params': {
            'tokens': 38,
            'coins': 45,
            'is_node': 1,
            'node_address': 'address',
            'last_transaction_id': 'uint26',
            'exist': 1,
        },
    },
    'TbdxmNLkwwdYaSbp': {
        'id': 'get-wallet-state',
        'result': '0',
        'params': {
            'tokens': 52,
            'coins': 79,
            'is_node': 1,
            'node_address': 'address',
            'last_transaction_id': 'uint76',
            'exist': 1,
        },
    },
    '0CbmvgcNg3obmWqj': {
        'id': 'get-wallet-state',
        'result': '0',
        'params': {
            'tokens': 58,
            'coins': 40,
            'is_node': 1,
            'node_address': 'address',
            'last_transaction_id': 'uint97',
            'exist': 1,
        },
    },
    'yZgww6wP4m7YGUF1': {
        'id': 'get-wallet-state',
        'result': '0',
        'params': {
            'tokens': 72,
            'coins': 65,
            'is_node': 1,
            'node_address': 'address',
            'last_transaction_id': 'uint77',
            'exist': 1,
        },
    },
    'uL5XaIRqJOXApLlQ': {
        'id': 'get-wallet-state',
        'result': '0',
        'params': {
            'tokens': 68,
            'coins': 63,
            'is_node': 1,
            'node_address': 'address',
            'last_transaction_id': 'uint69',
            'exist': 1,
        },
    },
    'WseZ8yOMgajWbktP': {
        'id': 'get-wallet-state',
        'result': '0',
        'params': {
            'tokens': 71,
            'coins': 77,
            'is_node': 1,
            'node_address': 'address',
            'last_transaction_id': 'uint61',
            'exist': 1,
        },
    },
    '1DYhX2TPEBRPA60f': {
        'id': 'get-wallet-state',
        'result': '0',
        'params': {
            'tokens': 34,
            'coins': 84,
            'is_node': 1,
            'node_address': 'address',
            'last_transaction_id': 'uint34',
            'exist': 1,
        },
    },
    '6TvbcCojCg2uSSnG': {
        'id': 'get-wallet-state',
        'result': '0',
        'params': {
            'tokens': 12,
            'coins': 26,
            'is_node': 1,
            'node_address': 'address',
            'last_transaction_id': 'uint57',
            'exist': 1,
        },
    },
    'tnPWxOZMkkBkkIP7': {
        'id': 'get-wallet-state',
        'result': '0',
        'params': {
            'tokens': 41,
            'coins': 94,
            'is_node': 1,
            'node_address': 'address',
            'last_transaction_id': 'uint88',
            'exist': 1,
        },
    },
    'jsImD8gVE9p9XMqb': {
        'id': 'get-wallet-state',
        'result': '0',
        'params': {
            'tokens': 34,
            'coins': 99,
            'is_node': 1,
            'node_address': 'address',
            'last_transaction_id': 'uint97',
            'exist': 1,
        },
    },
};